### ISSUE TITLE
Placebo's mod compatibility

### ISSUE THREAD

**Issue by Sereath** [friendlyhj/TinkersOreDictCache#1]
While the loading time of Tinkers was drastically reduced:

Without Tinkers OreDict Cache
![image](https://user-images.githubusercontent.com/54506307/145644760-7d4a008b-7f37-4e81-ba68-56360c854a7e.png)

Placebo's went the opposite way:

With Tinkers OreDict Cache
![image](https://user-images.githubusercontent.com/54506307/145644787-578f5bec-9476-481c-af84-97c3e6cf8430.png)

Changing this to false in Placebo's config file fixed it:
```
    # If placebo will replace all ShapelessRecipes and ShapelessOreRecipes with FastShapelessRecipes. [default: true]
    B:"Fast Shapeless Recipes"=false
```

![image](https://user-images.githubusercontent.com/54506307/145645214-b6b9e772-0db4-4dad-a089-6d82945d9400.png)

https://www.curseforge.com/minecraft/mc-mods/placebo

Just a heads up, so feel free to close this.

**Comment by friendlyhj** [comment]
I could not reproduce it. Placebo ran instantly (less than one second in post-init phase) in my modpack.
Placebo "hacks" shapeless recipes of vanilla, I changed smelting recipes. These are completely different things. I wonder why my mod influences placebo...
